//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdmx.Scg.Sancionados.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependencia
    {
        public int IdDependencia { get; set; }
        public string DescDependencia { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdUsuario { get; set; }
        public string Clave { get; set; }
        public bool IdEstatus { get; set; }
    }
}
