//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdmx.Scg.Sancionados.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoRepublica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoRepublica()
        {
            this.Municipio = new HashSet<Municipio>();
        }
    
        public int IdEstado { get; set; }
        public int IdPais { get; set; }
        public string DescEstado { get; set; }
        public bool IdEstatus { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Municipio> Municipio { get; set; }
    }
}
