//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cdmx.Scg.Sancionados.Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbContextSan : DbContext
    {
        public DbContextSan()
            : base("name=DbContextSan")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dependencia> Dependencia { get; set; }
        public virtual DbSet<EstadoRepublica> EstadoRepublica { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<EstatusImpugnacion> EstatusImpugnacion { get; set; }
        public virtual DbSet<EstatusSancion> EstatusSancion { get; set; }
        public virtual DbSet<Irregularidad> Irregularidad { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<TipoImpugnacion> TipoImpugnacion { get; set; }
        public virtual DbSet<TipoInscrito> TipoInscrito { get; set; }
        public virtual DbSet<TipoOficio> TipoOficio { get; set; }
        public virtual DbSet<TipoOrigen> TipoOrigen { get; set; }
        public virtual DbSet<TipoSancion> TipoSancion { get; set; }
    }
}
